class DWCError extends Error {
  code: string;

  constructor(code: string, message?: string) {
    super(message ?? code);
    this.name = "DWCError";
    this.code = code;
  }
}

const ERR_WORKER = "ERR_WORKER";
const ERR_BOOT_TIMEOUT = "ERR_BOOT_TIMEOUT";
const ERR_NOT_ISOLATED = "ERR_NOT_ISOLATED";
const ERR_NOT_IMPLEMENTED = "ERR_NOT_IMPLEMENTED";
const ERR_INTERNAL = "ERR_INTERNAL";
const ERR_NET_FETCH_FAILED = "ERR_NET_FETCH_FAILED";
const ERR_PREVIEW_CONNECTION_REFUSED = "ERR_PREVIEW_CONNECTION_REFUSED";
const ERR_PREVIEW_WS_HANDSHAKE_FAILED = "ERR_PREVIEW_WS_HANDSHAKE_FAILED";

export {
  DWCError,
  ERR_BOOT_TIMEOUT,
  ERR_INTERNAL,
  ERR_NET_FETCH_FAILED,
  ERR_NOT_IMPLEMENTED,
  ERR_NOT_ISOLATED,
  ERR_PREVIEW_CONNECTION_REFUSED,
  ERR_PREVIEW_WS_HANDSHAKE_FAILED,
  ERR_WORKER,
};
